# Generated by Django 5.2.15 on 2026-06-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="캠페인명")),
                (
                    "channel",
                    models.CharField(
                        choices=[("ALIMTALK", "알림톡")],
                        default="ALIMTALK",
                        max_length=20,
                        verbose_name="채널",
                    ),
                ),
                ("message_template", models.TextField(verbose_name="메시지")),
                ("is_ad", models.BooleanField(default=True, verbose_name="광고성")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "작성중"), ("sent", "발송완료")],
                        default="draft",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "recipient_count",
                    models.IntegerField(default=0, verbose_name="대상 수"),
                ),
                (
                    "sent_count",
                    models.IntegerField(default=0, verbose_name="발송 성공"),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, verbose_name="발송 실패"),
                ),
                (
                    "skipped_count",
                    models.IntegerField(default=0, verbose_name="제외(미동의 등)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="발송 시각"
                    ),
                ),
            ],
            options={
                "verbose_name": "캠페인",
                "verbose_name_plural": "캠페인",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="설명"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BRONZE", "브론즈"),
                            ("SILVER", "실버"),
                            ("GOLD", "골드"),
                        ],
                        default="",
                        help_text="비우면 전체 등급",
                        max_length=10,
                        verbose_name="등급",
                    ),
                ),
                (
                    "min_visits",
                    models.IntegerField(default=0, verbose_name="최소 방문 횟수"),
                ),
                (
                    "min_spent",
                    models.IntegerField(default=0, verbose_name="최소 누적 결제액"),
                ),
                (
                    "inactive_days",
                    models.IntegerField(default=0, verbose_name="휴면 기준(일)"),
                ),
                (
                    "require_opt_in",
                    models.BooleanField(
                        default=True, verbose_name="마케팅 수신 동의자만"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "세그먼트",
                "verbose_name_plural": "세그먼트",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="수신 번호")),
                ("rendered_message", models.TextField(verbose_name="발송 본문")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "성공"),
                            ("failed", "실패"),
                            ("skipped", "제외"),
                        ],
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="사유"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시각"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="marketing.campaign",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "발송 로그",
                "verbose_name_plural": "발송 로그",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="marketing.segment",
                verbose_name="세그먼트",
            ),
        ),
    ]
