# Generated by Django 5.2.17 on 2026-09-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="channel",
            field=models.CharField(
                choices=[("ALIMTALK", "문자")],
                default="ALIMTALK",
                max_length=20,
                verbose_name="채널",
            ),
        ),
    ]
