# Generated by Django 5.2.17 on 2026-09-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_alter_campaign_channel"),
        ("membership", "0026_coupon_menu_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="membership.member",
                verbose_name="직접 고른 수신자",
            ),
        ),
    ]
