# Generated by Django 5.2.15 on 2026-06-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="매장명")),
                (
                    "point_earn_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.05,
                        max_digits=4,
                        verbose_name="적립률",
                    ),
                ),
                (
                    "stamp_goal",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="스탬프 목표"
                    ),
                ),
                (
                    "stamp_reward_points",
                    models.PositiveIntegerField(
                        default=3000, verbose_name="스탬프 달성 보상 포인트"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "매장",
                "verbose_name_plural": "매장",
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="설명"),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("visit_count", "방문 횟수"),
                            ("total_spent", "누적 결제액"),
                        ],
                        max_length=20,
                        verbose_name="조건 유형",
                    ),
                ),
                ("target_value", models.IntegerField(verbose_name="목표값")),
                ("reward_points", models.IntegerField(verbose_name="보상 포인트")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="membership.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "미션",
                "verbose_name_plural": "미션",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="연락처(회원번호)"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("points", models.IntegerField(default=0, verbose_name="보유 포인트")),
                (
                    "total_spent",
                    models.IntegerField(default=0, verbose_name="누적 결제액"),
                ),
                (
                    "visit_count",
                    models.IntegerField(default=0, verbose_name="방문 횟수"),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("BRONZE", "브론즈"),
                            ("SILVER", "실버"),
                            ("GOLD", "골드"),
                        ],
                        default="BRONZE",
                        max_length=10,
                        verbose_name="등급",
                    ),
                ),
                ("stamps", models.IntegerField(default=0, verbose_name="스탬프")),
                (
                    "marketing_opt_in",
                    models.BooleanField(default=False, verbose_name="마케팅 수신 동의"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입 시각"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="membership.store",
                        verbose_name="매장",
                    ),
                ),
            ],
            options={
                "verbose_name": "회원",
                "verbose_name_plural": "회원",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_amount", models.IntegerField(verbose_name="주문 총액")),
                (
                    "points_used",
                    models.IntegerField(default=0, verbose_name="사용 포인트"),
                ),
                ("net_amount", models.IntegerField(verbose_name="실결제액")),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="적립 포인트"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("TOSS_CARD", "토스-카드"),
                            ("TOSS_EASY", "토스-간편결제"),
                            ("CASH", "현금"),
                        ],
                        max_length=20,
                        verbose_name="결제수단",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인 전"),
                            ("paid", "결제완료"),
                            ("canceled", "취소"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "toss_payment_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="토스 결제키",
                    ),
                ),
                (
                    "toss_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="주문 ID(멱등키)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인 시각"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="membership.member",
                        verbose_name="회원",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="membership.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래",
                "verbose_name_plural": "거래",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField(verbose_name="증감")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("earn", "적립"),
                            ("redeem", "사용"),
                            ("adjust", "조정"),
                            ("mission", "미션 보상"),
                            ("stamp", "스탬프 보상"),
                            ("cancel", "취소 원복"),
                        ],
                        max_length=10,
                        verbose_name="사유",
                    ),
                ),
                ("balance_after", models.IntegerField(verbose_name="반영 후 잔액")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시각"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_entries",
                        to="membership.member",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_entries",
                        to="membership.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "포인트 내역",
                "verbose_name_plural": "포인트 내역",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="진행값")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="달성"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="달성 시각"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_missions",
                        to="membership.member",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_missions",
                        to="membership.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "회원 미션",
                "verbose_name_plural": "회원 미션",
                "unique_together": {("member", "mission")},
            },
        ),
    ]
