# Generated by Django 5.2.15 on 2026-07-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="메뉴명")),
                ("price", models.IntegerField(verbose_name="가격")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("coffee", "커피"),
                            ("noncoffee", "논커피"),
                            ("ade", "티·에이드"),
                            ("dessert", "디저트"),
                        ],
                        default="coffee",
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, default="", max_length=8, verbose_name="이모지"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="판매중"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="정렬")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="membership.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "메뉴",
                "verbose_name_plural": "메뉴",
                "ordering": ["category", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="메뉴명(스냅샷)"),
                ),
                ("unit_price", models.IntegerField(verbose_name="단가")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="수량"),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="membership.menuitem",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="membership.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문 항목",
                "verbose_name_plural": "주문 항목",
            },
        ),
    ]
