# Generated by Django 5.2.15 on 2026-07-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_menuitem_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="decaf_available",
            field=models.BooleanField(default=False, verbose_name="디카페인 선택"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="oatmilk_available",
            field=models.BooleanField(default=False, verbose_name="오트밀크 선택"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="temp_option",
            field=models.CharField(
                choices=[
                    ("none", "선택없음"),
                    ("ice", "아이스만"),
                    ("hotice", "핫/아이스"),
                ],
                default="hotice",
                max_length=10,
                verbose_name="온도 옵션",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="decaf",
            field=models.BooleanField(default=False, verbose_name="디카페인"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="oatmilk",
            field=models.BooleanField(default=False, verbose_name="오트밀크"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="temperature",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="온도"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="option_price",
            field=models.IntegerField(default=500, verbose_name="옵션 추가금"),
        ),
        migrations.AddField(
            model_name="store",
            name="set_discount_amount",
            field=models.IntegerField(default=500, verbose_name="세트 할인액"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="discount",
            field=models.IntegerField(default=0, verbose_name="세트 할인"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("coffee", "커피"),
                    ("coldbrew", "콜드브루"),
                    ("ade", "스무디·에이드"),
                    ("noncoffee", "논커피"),
                    ("tea", "티"),
                    ("dessert", "디저트"),
                ],
                default="coffee",
                max_length=20,
                verbose_name="카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.IntegerField(verbose_name="단가(옵션 포함)"),
        ),
    ]
