# Generated by Django 5.2.15 on 2026-07-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "membership",
            "0003_menuitem_decaf_available_menuitem_oatmilk_available_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_open",
            field=models.BooleanField(default=False, verbose_name="영업중"),
        ),
        migrations.AddField(
            model_name="store",
            name="opened_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="영업 시작 시각"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="point_earn_rate",
            field=models.DecimalField(
                decimal_places=3, default=0.03, max_digits=4, verbose_name="적립률"
            ),
        ),
    ]
