# Generated by Django 5.2.15 on 2026-07-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0004_store_is_open_store_opened_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="shot_available",
            field=models.BooleanField(default=False, verbose_name="샷 추가 선택"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="stock",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="재고(빈칸=무제한)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="shot",
            field=models.BooleanField(default=False, verbose_name="샷 추가"),
        ),
    ]
