# Generated by Django 5.2.15 on 2026-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0005_menuitem_shot_available_menuitem_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="approval_no",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="단말 승인번호"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CARD", "카드"),
                    ("NAVERPAY", "네이버페이"),
                    ("EASYPAY", "간편결제"),
                    ("CASH", "현금"),
                    ("TOSS_CARD", "토스-카드(PG)"),
                    ("TOSS_EASY", "토스-간편(PG)"),
                ],
                max_length=20,
                verbose_name="결제수단",
            ),
        ),
    ]
