# Generated by Django 5.2.16 on 2026-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0007_transaction_uniq_paid_toss_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="cost",
            field=models.IntegerField(default=0, verbose_name="재료원가"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_cost",
            field=models.IntegerField(default=0, verbose_name="단가 원가(스냅샷)"),
        ),
        migrations.AddField(
            model_name="store",
            name="option_cost",
            field=models.IntegerField(default=0, verbose_name="옵션 추가 원가"),
        ),
        migrations.AddField(
            model_name="store",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=3, default=0.1, max_digits=4, verbose_name="부가세율"
            ),
        ),
    ]
