# Generated by Django 5.2.16 on 2026-08-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "membership",
            "0008_menuitem_cost_orderitem_unit_cost_store_option_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="초대 코드",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="membership.member",
                verbose_name="추천인",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="happy_end",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="해피아워 종료(시)"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="happy_multiplier",
            field=models.DecimalField(
                decimal_places=1,
                default=2.0,
                max_digits=3,
                verbose_name="해피아워 적립 배수",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="happy_start",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="해피아워 시작(시)"
            ),
        ),
        migrations.AlterField(
            model_name="pointentry",
            name="reason",
            field=models.CharField(
                choices=[
                    ("earn", "적립"),
                    ("redeem", "사용"),
                    ("adjust", "조정"),
                    ("mission", "미션 보상"),
                    ("stamp", "스탬프 보상"),
                    ("referral", "초대 보상"),
                    ("cancel", "취소 원복"),
                ],
                max_length=10,
                verbose_name="사유",
            ),
        ),
    ]
