# Generated by Django 5.2.16 on 2026-08-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0009_member_referral_code_member_referred_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, verbose_name="퀘스트 키")),
                (
                    "kind",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="유형"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="제목"
                    ),
                ),
                (
                    "reward_points",
                    models.IntegerField(default=0, verbose_name="지급 보상"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="달성 시각"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "개인 퀘스트 달성",
                "verbose_name_plural": "개인 퀘스트 달성",
                "ordering": ["-completed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "key"), name="uniq_member_quest"
                    )
                ],
            },
        ),
    ]
