# Generated by Django 5.2.16 on 2026-08-08 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0010_memberquest"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="referral_used_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="초대 사용 시각"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="spins",
            field=models.IntegerField(default=0, verbose_name="룰렛 기회"),
        ),
        migrations.AddField(
            model_name="member",
            name="tier_rewarded",
            field=models.CharField(
                choices=[("BRONZE", "브론즈"), ("SILVER", "실버"), ("GOLD", "골드")],
                default="BRONZE",
                max_length=10,
                verbose_name="등급 보상 지급분",
            ),
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("discount_5", "5% 할인"),
                            ("discount_10", "10% 할인"),
                            ("bogo", "음료 1+1"),
                            ("free_drink", "무료 음료"),
                            ("beans_200", "원두 200g"),
                        ],
                        max_length=20,
                        verbose_name="종류",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("roulette", "룰렛"),
                            ("tier", "등급 승급"),
                            ("ranking", "월간 랭킹"),
                            ("manual", "수기 지급"),
                        ],
                        default="roulette",
                        max_length=20,
                        verbose_name="발행 사유",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="메모"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="발행 시각"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="만료 시각"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="사용 시각"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="membership.member",
                        verbose_name="회원",
                    ),
                ),
                (
                    "used_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupons",
                        to="membership.transaction",
                        verbose_name="사용 거래",
                    ),
                ),
            ],
            options={
                "verbose_name": "쿠폰",
                "verbose_name_plural": "쿠폰",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "used_at"],
                        name="membership__member__2774aa_idx",
                    )
                ],
            },
        ),
    ]
