# Generated by Django 5.2.17 on 2026-08-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0011_member_referral_used_at_member_spins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="happy_multiplier",
            field=models.DecimalField(
                decimal_places=1,
                default=1.5,
                max_digits=3,
                verbose_name="해피아워 적립 배수",
            ),
        ),
    ]
