# Generated by Django 5.2.17 on 2026-08-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0012_alter_store_happy_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="recipe",
            field=models.TextField(blank=True, default="", verbose_name="레시피"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="recipe_hot",
            field=models.TextField(blank=True, default="", verbose_name="레시피(HOT)"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="recipe_note",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="비고(잔·분쇄도 등)",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="topping",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="토핑·데코"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="prep_notes",
            field=models.TextField(blank=True, default="", verbose_name="공통 밑작업"),
        ),
    ]
