# Generated by Django 5.2.17 on 2026-09-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0013_menuitem_recipe_menuitem_recipe_hot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="size_up_price",
            field=models.IntegerField(default=0, verbose_name="사이즈업 추가금"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_up",
            field=models.BooleanField(default=False, verbose_name="사이즈업"),
        ),
    ]
