# Generated by Django 5.2.17 on 2026-09-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0014_menuitem_size_up_price_orderitem_size_up"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="discount_rates",
            field=models.CharField(
                blank=True, default="5,10", max_length=50, verbose_name="수기 할인율(%)"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="manual_discount_pct",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="수기 할인율"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="discount",
            field=models.IntegerField(default=0, verbose_name="할인 합계"),
        ),
    ]
