# Generated by Django 5.2.17 on 2026-09-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "membership",
            "0015_store_discount_rates_transaction_manual_discount_pct_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="signup_bonus_points",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="가입 축하 포인트"
            ),
        ),
        migrations.AlterField(
            model_name="pointentry",
            name="reason",
            field=models.CharField(
                choices=[
                    ("earn", "적립"),
                    ("redeem", "사용"),
                    ("adjust", "조정"),
                    ("mission", "미션 보상"),
                    ("stamp", "스탬프 보상"),
                    ("referral", "초대 보상"),
                    ("signup", "가입 축하"),
                    ("cancel", "취소 원복"),
                ],
                max_length=10,
                verbose_name="사유",
            ),
        ),
    ]
