# Generated by Django 5.2.17 on 2026-09-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0017_coupon_discount_rates_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="stamp_reward_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="사용하지 않는 값입니다. 스탬프를 다 모으면 룰렛 기회 1번이 지급됩니다.",
                verbose_name="스탬프 보상 포인트(미사용)",
            ),
        ),
    ]
