# Generated by Django 5.2.17 on 2026-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0020_import_payhere_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="baseline_total_spent",
            field=models.IntegerField(default=0, verbose_name="이관 시점 누적결제"),
        ),
        migrations.AddField(
            model_name="member",
            name="baseline_visit_count",
            field=models.IntegerField(default=0, verbose_name="이관 시점 방문수"),
        ),
    ]
