# Generated by Django 5.2.17 on 2026-09-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0022_backfill_baseline_and_mission"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="split_amount",
            field=models.IntegerField(default=0, verbose_name="분할 금액"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="split_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARD", "카드"),
                    ("NAVERPAY", "네이버페이"),
                    ("EASYPAY", "간편결제"),
                    ("CASH", "현금"),
                    ("TOSS_CARD", "토스-카드(PG)"),
                    ("TOSS_EASY", "토스-간편(PG)"),
                ],
                default="",
                max_length=20,
                verbose_name="분할 결제수단",
            ),
        ),
    ]
