# Generated by Django 5.2.17 on 2026-09-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0025_pin_mission_rewards"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                help_text="비우면 음료 전체",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupons",
                to="membership.menuitem",
                verbose_name="사용 가능 메뉴",
            ),
        ),
    ]
