# Generated by Django 5.2.17 on 2026-09-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0026_coupon_menu_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.TextField(blank=True, default="", verbose_name="메뉴판 사진"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="show_on_board",
            field=models.BooleanField(default=True, verbose_name="메뉴판에 표시"),
        ),
    ]
