# Generated by Django 5.2.17 on 2026-09-19 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0028_board_hide_carryover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="이름(관리용)",
                    ),
                ),
                ("image", models.TextField(verbose_name="이미지")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="메뉴판에 표시"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="정렬")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록 시각"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promos",
                        to="membership.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로모션",
                "verbose_name_plural": "프로모션",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
