# Generated by Django 5.2.17 on 2026-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0029_promo"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="set_eligible",
            field=models.BooleanField(default=False, verbose_name="세트 할인 대상"),
        ),
    ]
