# Generated by Django 5.2.17 on 2026-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0032_menu_sync_v2"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status", "paid_at"], name="tx_status_paid_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["member", "paid_at"], name="tx_member_paid_idx"),
        ),
    ]
